@ECHO OFF
set BASEDIR=..\..
set TESTDIR=%BASEDIR%\function-test
set SOURCEDIR=%TESTDIR%\testcases
set TARGETDIR=%TESTDIR%\bin
set LIBDIR=%BASEDIR%\target
set EXTJARDIR=%TESTDIR%\extjar
set CLASSPATH=%TARGETDIR%
set CLASSPATH=%CLASSPATH%;%LIBDIR%\dependency\commons-logging-1.1.1.jar
set CLASSPATH=%CLASSPATH%;%LIBDIR%\dependency\log4j-1.2.15.jar
set CLASSPATH=%CLASSPATH%;%LIBDIR%\terasoluna-logger-1.0.0.jar
set SOURCES=%sourcedir%\common\*.java
set COMMONCONF=%TESTDIR%\conf\common
set CASECONF=%TESTDIR%\conf\case%TESTNO%
set MAIN=common.Main
@ECHO ON