

TRUNCATE TABLE PRODUCT_ORDER;
TRUNCATE TABLE PRODUCT_ORDER_DETAILS;

INSERT INTO PRODUCT_ORDER(ORDR_ID, ORDR_DATE, CUST_ID) VALUES ('1', TIMESTAMP '2011-05-26 17:58:46.891', '0001');
INSERT INTO PRODUCT_ORDER(ORDR_ID, ORDR_DATE, CUST_ID) VALUES ('2', TIMESTAMP '2011-05-26 18:06:56.297', '0002');
INSERT INTO PRODUCT_ORDER(ORDR_ID, ORDR_DATE, CUST_ID) VALUES ('3', TIMESTAMP '2011-05-26 18:07:24.709', '0003');
INSERT INTO PRODUCT_ORDER(ORDR_ID, ORDR_DATE, CUST_ID) VALUES ('4', TIMESTAMP '2011-05-26 18:08:03.347', '0004');

INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('1', '1', 'T01', 20);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('1', '2', 'T02', 30);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('1', '3', 'T03', 40);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('2', '1', 'T04', 10);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('2', '2', 'T05', 20);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('2', '3', 'T06', 30);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('3', '1', 'T07', 15);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('3', '2', 'T08', 25);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('3', '3', 'T09', 35);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('4', '1', 'T10', 12);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('4', '2', 'T11', 22);
INSERT INTO PRODUCT_ORDER_DETAILS(ORDR_ID, DETL_ID, PROD_ID, QUANTITY) VALUES ('4', '3', 'T12', 32);


commit;
