-- 
-- TABLE: DBMESSAGES
--
--DROP TABLE DBMESSAGES;

CREATE TABLE DBMESSAGES (
    ID             integer  NOT NULL,
    CODE           VARCHAR(32)  NOT NULL,
    LANGUAGES      VARCHAR(32),
    CONTRY         VARCHAR(32),
    VARIANT        VARCHAR(32),   
    MESSAGE        VARCHAR(256),
    CONSTRAINT PK_DBMESSAGES PRIMARY KEY (ID)
);

