package jp.terasoluna.fw.collector;

/** This file was automatically generated. */
public final class LogId {
    /**
     * <strong>TAL041001 = {0}</strong>
     */
    public static final String TAL041001 = "TAL041001";
    /**
     * <strong>TAL041002 = Interrupt was generated. thread:[{0}]</strong>
     */
    public static final String TAL041002 = "TAL041002";
    /**
     * <strong>TAL041003 = skip queue</strong>
     */
    public static final String TAL041003 = "TAL041003";
    /**
     * <strong>TAL041007 = next() value:[null] queue size:[{0}]</strong>
     */
    public static final String TAL041007 = "TAL041007";
    /**
     * <strong>TAL041008 = peekNext() value:[null] queue size:[{0}]</strong>
     */
    public static final String TAL041008 = "TAL041008";
    /**
     * <strong>TAL041012 = setFinish(). thread:[{0}]</strong>
     */
    public static final String TAL041012 = "TAL041012";
    /**
     * <strong>TAL041013 = It was not able to add to queue.  isFinish():[{0}] isDone():[{1}] dataValueObject datacount:[{2}]</strong>
     */
    public static final String TAL041013 = "TAL041013";
    /**
     * <strong>TAL041014 = isFinish() is true and queue is empty.</strong>
     */
    public static final String TAL041014 = "TAL041014";
    /**
     * <strong>TAL041018 = FileCollector is finish. datacount:[{0}]</strong>
     */
    public static final String TAL041018 = "TAL041018";
    /**
     * <strong>TAL041019 = getNext() wait {0} msec.</strong>
     */
    public static final String TAL041019 = "TAL041019";
    /**
     * <strong>DAL041001 = {0}</strong>
     */
    public static final String DAL041001 = "DAL041001";
    /**
     * <strong>DAL041002 = {0}. thread:[{1}]</strong>
     */
    public static final String DAL041002 = "DAL041002";
    /**
     * <strong>IAL041001 = {0}</strong>
     */
    public static final String IAL041001 = "IAL041001";
    /**
     * <strong>WAL041001 = {0}</strong>
     */
    public static final String WAL041001 = "WAL041001";
    /**
     * <strong>WAL041002 = The property is not found. property name:[{0}] class name:[{1}] message:[{2}]</strong>
     */
    public static final String WAL041002 = "WAL041002";
    /**
     * <strong>WAL041003 = An interrupt occurs.</strong>
     */
    public static final String WAL041003 = "WAL041003";
    /**
     * <strong>WAL041004 = The exception is generated by the exception handler.</strong>
     */
    public static final String WAL041004 = "WAL041004";
    /**
     * <strong>EAL041001 = {0}</strong>
     */
    public static final String EAL041001 = "EAL041001";
    /**
     * <strong>FAL041001 = {0}</strong>
     */
    public static final String FAL041001 = "FAL041001";
}
